// flow-typed signature: a2fe7c3c82225bb2a0b60ccf2be1ba73
// flow-typed version: <<STUB>>/eslint-config-b8ta_v^2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-b8ta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-b8ta' {
  declare module.exports: any;
}
