// flow-typed signature: 6b34e42f7d4cd4a13166b3478eaed2af
// flow-typed version: <<STUB>>/postcss-advanced-variables_v^1.2.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-advanced-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-advanced-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-advanced-variables/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-advanced-variables/index' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
declare module 'postcss-advanced-variables/index.js' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
declare module 'postcss-advanced-variables/test/index.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/test/index'>;
}
